FROM golang:1.22-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/ cmd/
COPY internal/ internal/
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /tracker ./cmd/tracker

FROM alpine:3.20
RUN adduser -D app
USER app
WORKDIR /home/app
COPY --from=builder /tracker /usr/local/bin/tracker
ENV TRACKER_ADDR=:7070
EXPOSE 7070
ENTRYPOINT ["tracker"]

